src/Entity/Recall.php
<?php

namespace App\Entity;

use App\Repository\RecallRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecallRepository::class)]
class Recall
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\ManyToOne(targetEntity: Box::class, inversedBy: 'list')]
    private $target_box;
    
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $status;

    #[ORM\ManyToOne(targetEntity: Status::class, inversedBy: 'status_name', cascade:["persist"] )]
    private $state;
    
    private $boxName;

    #[ORM\Column(type: 'string', length: 2048)]
    private $description;

    public function getBoxName(): ?string
    {
        return $this->boxName;
    }

    public function setBoxName(string $boxName): self
    {
        $this->boxName = $boxName;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTargetBox(): ?Box
    {
        return $this->target_box;
    }

    public function setTargetBox(?Box $target_box): self
    {
        $this->target_box = $target_box;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getState(): ?Status
    {
        return $this->state;
    }

    public function setState(?Status $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    
}

src/Controller/RememberController.php
<?php

namespace App\Controller;

use App\Entity\Box;
use App\Form\Type\CreateType;
use App\Repository\StatusRepository;
use App\Service\RememberManager;
use App\Service\StatusHelper;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class RememberController extends AbstractController 
{
    /**
     * @Route("/", name="index")
     */
    public function showIndex(ManagerRegistry $doctrine, Request $boxRequest, StatusRepository $statusRepository, RememberManager $rememberManager, StatusHelper $statusHelper): Response
    {
        $box = new Box();
        $box->setName('New box');
        $entityManager = $doctrine->getManager();
        $form = $this->createForm(CreateType::class,$box);
        $form->handleRequest($boxRequest);
        $log = '';
        
        if($form->get('new')->isClicked())
        {
            $entityManager->persist($box);
            $entityManager->flush();
        }

        if($form->get('recall')->isClicked())
        {
            $boxName = $form->get('boxName')->getData();
            $log = $rememberManager->addRecall($boxName);
        }
        $items = $rememberManager->getItems();
        $statusList = $statusHelper->generateIcons();

        return $this->renderForm('remember/index.html.twig',[
            'form' => $form,
            'boxes' => $items['boxes'],
            'recalls' => $items['recalls'],
            'status' => $statusList['status'],
            'statusIcons' => $statusList['icons'],
            'log' => $log,
        ]);
    }

    /**
     * @Route("/status", name="status")
     */
    public function showStatus(StatusRepository $statusRepository, StatusHelper $statusHelper): Response
    {
        $status = $statusRepository->findAll();
        $stateMain = $statusRepository->getMain();
        $statusList = $statusHelper->generateIcons();
        return $this->renderForm('remember/status.html.twig',[
            'status' => $statusList['status'],
            'stateMain' => $stateMain,
            'icons' => $statusList['icons']]);
    }

}

templates/remember/edit.html.twig
    <div id="editBox" class="box col" 
        data-controller="box"
        >
        {{ form_start(editForm) }}
        <div id="edit_box" class="form-group">
        {{form_row(editForm.name)}}
        </div>
        <div class="form-group">
            {#}{{ form_widget(editForm.list, {'attr': {
            {{ form_widget(editForm.list, {'attr': {
                'data-box-target': 'list',
                'data-index': "{{ editForm.list|length > 0 ? editForm.list|last.vars.name + 1 : 0 }}",
                'data-prototype' : "{{ form_widget(editForm.list.vars.prototype)|e('html_attr') }}",
                }}) }}{#}
        </div>
        <div 
        data-index="{{ editForm.list|length > 0 ? editForm.list|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(editForm.list.vars.prototype)|e('html_attr') }}"
        data-box-target="list">
            {{form_row(editForm.list)}}
        </div>
        <div id="edit_buttons" class="form-group">
            <button class="btn btn-secondary" type="button" data-action="click->box#addRecall"  data-collection-holder-class="recalls">Add a recall</button>
            {{ form_rest(editForm) }}
        </div>
    </div>

templates/remember/editState.html.twig
{{ form_start(editForm) }}
    <td>{{form_row(editForm.name)}}</td>
    <td>{{form_row(editForm.priority)}}</td>
    <td>{{form_row(editForm.icon)}}</td>
    <td class="stateButton">{{form_row(editForm.save)}}</td>
    <td class="stateButton">{{form_row(editForm.exit)}}</td>
{{ form_rest(editForm)}}

templates/remember/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div id="base">
    {% if log is defined %}
    <p class="log">{{log}}</p>
    {% endif %}
    <div id="appContent">
        {% if form is defined %}
        <div id="recallsMenu" class="container">
            <h4>Box Options</h4>
            {{ form_start(form) }}
            <div class="row">
                <div class="col-3">
                {{form_row(form.name)}}
                </div>
                <div class="col-3">
                {{form_row(form.new)}}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    {{form_row(form.boxName)}}
                </div>
                <div class="col-3">
                    {{form_row(form.recall)}}
                </div>
            </div>
            {{form_rest(form)}}
            {{form_end(form)}}            
        </div>
        {% endif %}
        <h4>Status options</h4>
        <a class="pageLink" href="status">Configure status</a>
        {% if boxes is defined %}
        <div id="boxes" class="container">
            <div class="row">
                {% for box in boxes %}
                {#}Box is edited in the main page{#}
                    {% if editBox is defined and editBox == box %}
                    {{ include('remember/edit.html.twig') }}
                    {% else %}
                    <div 
                        data-controller="box"
                        class="box col">
                            <p class="boxTitle">{{box.name}}</p>
                            <a href="/delBox/{{box.id}}" title="Delete"><i class="bi bi-dash-circle-fill" style="font-size: 2rem; color: cornflowerblue;"></i></a>
                            <a href="/updBox/{{box.id}}" title="Edit box"><i class="bi bi-gear-fill" style="font-size: 2rem; color: cornflowerblue;"></i></a>
                        <div class="recalls">
                        {% for state in status %}
                            {% if state.name != "done" %}
                                <p class="state_title">{{state.name}}</p>
                            {% endif %}
                            {% for recall in recalls %}
                                {% if box == recall.targetBox and recall.status == state.name %}
                                    {% if recall.status == "urgent" %}
                                        <div class="rec_urgent">
                                    {% elseif  recall.status == "done" %}
                                        <div data-box-target="done" class="rec_done">
                                    {% endif %}
                                    <p>
                                        <span onclick="document.getElementById('desc{{recall.id}}').classList.toggle('rec_display')" class="rec_name" title="show details">{{recall.name}}</span>
                                        <a href="/delRec/{{recall.id}}" title="delete"><i class="bi bi-patch-minus-fill" style="font-size: 1.2rem; color: cornflowerblue;"></i></a>
                                        {% if recall.status != "done" %}
                                            {% for state in status %}
                                                {% if state.name != "done" %}
                                                    <a href="/updRec/{{recall.id}}/{{state.name}}" title={{state.name}}><i class="bi {{ statusIcons[state.icon] }}" style="font-size: 1.2rem; color: burlywood;"></i></a>
                                                    {% else %}
                                                    <a href="/updRec/{{recall.id}}/{{state.name}}" title={{state.name}}><i class="bi {{ statusIcons[state.icon] }}" style="font-size: 1.2rem; color: darkseagreen;"></i></a>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </p>
                                    {% if recall.status == "urgent" or recall.status == "done" %}
                                        </div>
                                    {% endif %}
                                    
                                    {% if recDesc is defined and recDesc == recall %}
                                        {{ form(editDesc) }}
                                    {% endif %}
                                    <div id="desc{{recall.id}}" class="rec_display">
                                        <textarea readonly class="rec_desc">{{recall.description}}</textarea>
                                        {% if recall.status != "done" %}
                                            <a class="pageLink" href="updDesc/{{recall.id}}">Modify</a>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                        <button data-action="click->box#show" data-box-target="showButton" id="show_button">Show done recalls</button>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
                {% if desc is defined %}
                    {{ form(desc) }}
                {% endif %}
            </div>
        </div>
        {% else %}
        <p>No boxes added</p>
        {% endif %}
    </div>
    </div>
{% endblock %}

templates/remember/status.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% if log is defined %}
    <p class="log">{{log}}</p>
{% endif %}
{% if status is defined %}
    <h3>Status list</h3>
    <p>(Click name to set default) Default: {{stateMain.name}} </p>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>name</th>
                <th>Priority</th>
                <th>Icon</th>
                <th colspan="3">Options</th>
            </tr>
        </thead>
        <tbody>
    {% for state in status %}
        {% if editState is defined and editState == state %}
            {{ include('remember/editState.html.twig') }}
        {% else %}
        <tr>
            <td><a class="stateName" href="/status/setMain/{{state.id}}">{{state.name}}</a></td>
            <td>{{state.priority}}</td>
            <td><i class="bi {{ icons[state.icon] }}" style="font-size: 1.2rem;"></i></td>
            <td>
            {% if state.active == 0 %}
                <a href="/status/active/{{state.id}}">Activate</a>
                {% else %}
                <a href="/status/deactive/{{state.id}}">Deactivate</a>
            {% endif %}
            </td>
            {% if state.id > 3 %}
            <td><a href="/status/edState/{{state.id}}">edit</td>
            <td><a href="/status/delState/{{state.id}}">delete</td>
            {% endif %}
        </tr>
        {% endif %}
    {% endfor %}
    {% if addForm is defined %}
        <tr>
        {{ form_start(addForm) }}
            <td>{{ form_row(addForm.name) }}</td>
            <td>{{ form_row(addForm.priority) }}</td>
            <td>{{ form_row(addForm.icon)}}</td>
            <td class="stateButton" colspan="2">{{ form_row(addForm.add) }}</td>
        {{ form_rest(addForm) }}
        </tr>
    {% endif %}
        </tbody>
    </table>
{% else %}
<p>No status found</p>
{% endif %}
{% if addForm is not defined %}
    <button id="create_state"><a href="status/addState">New state</a></button>
{% else %}
<a class="pageLink" href="/status">Return</a>
{% endif %}
<a class="pageLink" href="/">Go to main</a>
{% endblock %}